(define (sorted? hlist)
    (or (< (length hlist) 2)
        (and (<=(car hlist)
                (cadr hlist))
            (sorted? (cdr hlist))
        )
    )
)
(display (sorted? `(1 2 3 4 5 6)))(newline)